### ISSUE TITLE
macOS docker-compose up fails

### ISSUE THREAD

**Issue by MattiL** [lukebakken/docker-rabbitmq-cluster#2]
docker-compose up
...
Attaching to docker-rabbitmq-cluster-haproxy-1, docker-rabbitmq-cluster-perf-test-1, docker-rabbitmq-cluster-rmq0-1, docker-rabbitmq-cluster-rmq1-1, docker-rabbitmq-cluster-rmq2-1
docker-rabbitmq-cluster-rmq0-1       | chown: changing ownership of '/var/lib/rabbitmq/mnesia': Operation not permitted
docker-rabbitmq-cluster-rmq0-1       | chown: changing ownership of '/var/lib/rabbitmq/mnesia/.gitkeep': Operation not permitted
docker-rabbitmq-cluster-rmq2-1       | chown: changing ownership of '/var/lib/rabbitmq/mnesia': Operation not permitted
docker-rabbitmq-cluster-rmq2-1       | chown: changing ownership of '/var/lib/rabbitmq/mnesia/.gitkeep': Operation not permitted
docker-rabbitmq-cluster-rmq1-1       | chown: changing ownership of '/var/lib/rabbitmq/mnesia': Operation not permitted
docker-rabbitmq-cluster-rmq1-1       | chown: changing ownership of '/var/lib/rabbitmq/mnesia/.gitkeep': Operation not permitted
docker-rabbitmq-cluster-haproxy-1    | [NOTICE]   (1) : New worker (3) forked
docker-rabbitmq-cluster-haproxy-1    | [NOTICE]   (1) : Loading success.
docker-rabbitmq-cluster-haproxy-1    | [WARNING]  (3) : Server rabbitmq/rmq0 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 25ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
docker-rabbitmq-cluster-rmq2-1 exited with code 1
docker-rabbitmq-cluster-rmq1-1 exited with code 1
docker-rabbitmq-cluster-rmq0-1 exited with code 1
docker-rabbitmq-cluster-haproxy-1    | [WARNING]  (3) : Server rabbitmq/rmq1 is DOWN, reason: Layer4 connection problem, info: "No route to host", check duration: 3115ms. 1 active and 0 backup servers left. 1 sessions active, 0 requeued, 0 remaining in queue.
docker-rabbitmq-cluster-haproxy-1    | [WARNING]  (3) : Server mgmt/rmq1 is DOWN, reason: Layer4 connection problem, info: "No route to host", check duration: 627ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
docker-rabbitmq-cluster-haproxy-1    | [WARNING]  (3) : Server rabbitmq/rmq2 is DOWN, reason: Layer4 connection problem, info: "No route to host", check duration: 3056ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
docker-rabbitmq-cluster-haproxy-1    | [ALERT]    (3) : proxy 'rabbitmq' has no server available!
docker-rabbitmq-cluster-haproxy-1    | [WARNING]  (3) : Server mgmt/rmq2 is DOWN, reason: Layer4 connection problem, info: "No route to host", check duration: 553ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
docker-rabbitmq-cluster-haproxy-1    | [WARNING]  (3) : Server mgmt/rmq0 is DOWN, reason: Layer4 timeout, check duration: 5003ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
docker-rabbitmq-cluster-haproxy-1    | [ALERT]    (3) : proxy 'mgmt' has no server available!
docker-rabbitmq-cluster-perf-test-1  | Could not connect to broker(s) in 30 second(s), exiting.

**Comment by lukebakken** [comment]
```
chown: changing ownership of '/var/lib/rabbitmq/mnesia': Operation not permitted
```

You have a permission issue. Instead of `docker compose up`, run `make up`

Please read the code in this repository, including the `Makefile`.
