### ISSUE TITLE
unknow flag: --build-arg

### ISSUE THREAD

**Issue by Claude-Zq** [lukebakken/docker-rabbitmq-cluster#3]
I clone the entire repository to the server and make up, which outputs this error message
<img width="478" alt="image" src="https://user-images.githubusercontent.com/86907968/229137455-e01f8601-318c-483c-a98e-7d5cc39b14df.png">

**Comment by lukebakken** [comment]
The version of docker you're using probably doesn't support `--build-arg`.

What version of docker and docker compose are you using?

**Comment by Claude-Zq** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/86907968/229436163-605d2a9e-c31b-4a48-aa61-f7b9e4ef2f6a.png">

**Comment by lukebakken** [comment]
I will check my environment next week.

**Comment by Claude-Zq** [comment]
thx

**Comment by lukebakken** [comment]
Here are the versions that this project is compatible with:

```
$ docker --version
Docker version 23.0.3, build 3e7cbfdee1

$ docker compose version
Docker Compose version 2.17.2
```
